version: '3.2'

services:
  nextcloud_db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ../../docker/nextcloud/database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - mysql_root_password
      - mysql_password

  nextcloud_app:
    image: nextcloud
    restart: always
    ports:
      - 82:80
    volumes:
      - ../../docker/nextcloud/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - nextcloud_db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_password

networks:
  default:
    external: 
      name: reverseproxy

secrets:
  nextcloud_admin_password:
    file: .secrets/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: .secrets/nextcloud_admin_user.txt 
  mysql_root_password:
    file: .secrets/mariadb_root_password.txt
  mysql_password:
    file: .secrets/mariadb_password.txt