version: '3.2'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - ./database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    secrets:
      - mysql_root_password
      - mysql_password

  app:
    image: nextcloud
    restart: always
    ports:
      - 82:80
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD_FILE=/run/secrets/mysql_password
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
      - mysql_password

networks:
  default:
    external: 
      name: reverseproxy

secrets:
  nextcloud_admin_password:
    file: .secrets/nextcloud_admin_password.txt # put admin password to this file
  nextcloud_admin_user:
    file: .secrets/nextcloud_admin_user.txt # put admin username to this file
  mysql_root_password:
    file: .secrets/mariadb_root_password.txt
  mysql_password:
    file: .secrets/mariadb_password.txt