---
version: "3"
services:
  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=1000
      - PGID=1000
      - branch="v2-master"
      - fpm="false"
    ports:
      - 87:80
    volumes:
      - ../../docker/organizr/config:/config
    restart: unless-stopped
    
networks:
  default:
    external: 
      name: reverseproxy