version: "3.7"
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    network_mode: bridge
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8000:8000/tcp # Built-in HTTP control server
      - 8112:8112/tcp #deluge
    # command:
    volumes:
      - ../../docker/gluetun:/gluetun
    secrets:
      - openvpn_user
    environment:
      # More variables are available, see the readme table
      - VPNSP=mullvad
      - OPENVPN_USER_FILE=/run/secrets/openvpn_user
      - COUNTRY=Netherlands
      - City=Amsterdam
      - ISP=31173
      - FIREWALL_VPN_INPUT_PORTS=55435
      # Timezone for accurate logs times
      - TZ=Europe/Amsterdam
    restart: always
  deluge:
    image: ghcr.io/linuxserver/deluge
    container_name: deluge
    network_mode: "service:gluetun"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - ../../docker/deluge/config:/config
      - ../../docker/deluge/downloads:/downloads
    restart: unless-stopped

networks:
  default:
    external: 
      name: reverseproxy

secrets:
  openvpn_user:
    file: .secrets/openvpn_user.txt