version: '3'

services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    ports:
      - "81:8181"
      - "80:8080"
      - "443:4443"
    volumes:
      - "../../docker/nginx-proxy-manager/appdata:/config:rw"

networks:
  default:
    external:
      name: reverseproxy
